#ifndef __BUILD_TARGET_H__
#define __BUILD_TARGET_H__

#include "ccc/config.h"
#include "ccc/dependency.h"

#include <filesystem>
#include <source_location>
#include <string>
#include <utility>
#include <vector>

namespace ccc {

/* The base class of all build targets.  */
class build_target : public ccc::config_manager {
  public:
    /**
     * @brief Construct a new build target object.
     *
     * @param name The name of the target.
     * @param description The description of the target.
     * @param loc The location of the target.
     */
    build_target(std::string name, std::string description,
                 std::source_location loc);

    /**
     * @brief Construct a new build target object by copying another
     *        target object.
     *
     * @param other The build target object to be copied.
     */
    build_target(const build_target& other)
        : config_manager(other.config), name(other.name),
          output_path(other.output_path), obj_path(other.obj_path),
          source_files(other.source_files), obj_files(other.obj_files),
          lib_files(other.lib_files), dependencies(other.dependencies),
          loc(other.loc), status(other.status), loc_info(other.loc_info) {};

    /* The name of the target. The final product is output_path / name. */
    std::string name;

    /* The directory for the final product. */
    std::filesystem::path output_path;

    /* The path for storing intermediate products. */
    std::filesystem::path obj_path = "./build/obj/";

    /* The source files of the target. */
    std::vector<std::filesystem::path> source_files;

    /* The intermediate products of the target.(Automatically generated by the
     * build_target class based on the source files, or can be added by
     * oneself.) */
    std::vector<std::filesystem::path> obj_files;

    /* This variable stores the name of the library required for this target. */
    std::vector<std::string> lib_files;

    /* The dependencies of the target. */
    std::vector<std::pair<ccc::build_target*, dependency_description>>
        dependencies;

    /* The location of the project */
    std::source_location loc;

    /* The status of the target. */
    std::vector<std::string> status;

    /* The simple information of the location. */
    std::string loc_info;

    /**
     * @brief Add a dependency to the build target.
     *
     * @param dep The dependency of the target.
     * @param is_transmit Whether add it directly to the build target.
     * @param is_compile Whether to actively  dependencies, if
     *                   dependencies do not exist.
     */
    void add_dependency(const ccc::build_target* dep, bool is_transmit,
                        bool is_compile = false) {
        dependencies.push_back(std::make_pair(
            const_cast<ccc::build_target*>(dep),
            ccc::dependency_description(is_transmit, is_compile)));
    }

    /**
     * @brief Compile all source files in source_files.
     *
     * @param project_cfg The config of the father project.
     * @param path The path indicating the compilation order relationship.
     */
    virtual void compile(const ccc::config& project_cfg,
                         std::vector<std::string>& path) final;

    /**
     * @brief The subclass needs to initialize the unset information in this
     * method based on the existing information.
     *
     * @param project_cfg The config of the father project.
     */
    virtual void init(const ccc::config& project_cfg) = 0;

    /**
     * @brief The subclass needs to implement this function, and the linking
     *        operation of the subclass needs to be implemented in this
     *        function.
     *
     * @param project_cfg The config of the father project.
     */
    virtual void link(const ccc::config& project_cfg) = 0;

    /**
     * @brief This method would call the compile and link methods.
     *
     * @param project_cfg The config of the father project.
     * @param path The path indicating the compilation order relationship.
     */
    virtual void process(const ccc::config& project_cfg,
                         std::vector<std::string>& path) final;

    /**
     * @brief The subclass needs to implement this function. When the parent
     * target wants to add a subtask directly to itself, this method will be
     * called.
     *
     * @param super The parent target.
     */
    virtual void transmit(ccc::build_target& super) = 0;

    /* The convenient utility functions provided by ccc. */

    /**
     * @brief Add file_path to the source_files variable.
     *
     * @param file_path The file_path need to be added to the source_files
     *        variable.
     */
    virtual void add_source_file(const std::string& file_path) final;

    /**
     * @brief Add these file_paths to the source_files variable.
     *
     * @param file_paths The file_paths need to be added to the source_files
     *        variable.
     */
    virtual void add_source_files(
        const std::initializer_list<std::string>& file_paths) final;

    /**
     * @brief Add all files in the dir_paths which have the suffix in suffixs to
     *        the the source_files variable.(Default recursion into subfolders.)
     *
     * @param dir_paths The dir_paths which have the files need to be added to.
     * @param suffixs The suffixs of the files need to be added to the
     *        source_files variable.
     * @param recursive Decide whether to recursively enter subfolders.
     */
    virtual void
    add_source_files(const std::initializer_list<std::string>& dir_paths,
                     const std::initializer_list<std::string>& suffixs,
                     bool recursive = true) final;

    /**
     * @brief Add all files in the dir_paths which satisfy the judge function to
     *        the the source_files variable.(Default recursion into subfolders.)
     *
     * @param dir_paths The dir_paths which have the files need to be added to.
     * @param judge The function which decides whether to add the file.
     * @param recursive Decide whether to recursively enter subfolders.
     */
    virtual void
    add_source_files(const std::initializer_list<std::string>& dir_paths,
                     auto judge(const std::string&)->bool,
                     bool recursive = true) final;

    /**
     * @brief Remove file_path from the source_files variable.
     *
     * @param file_path The file_path need to be removed from the source_files
     *        variable.
     */
    virtual void remove_source_file(const std::string& file_path) final;

    /**
     * @brief Remove these file_paths from the source_files variable.
     *
     * @param file_paths The file_paths need to be removed from the source_files
     *        variable.
     */
    virtual void remove_source_files(
        const std::initializer_list<std::string>& file_paths) final;

    /**
     * @brief Remove all files in the source_files variable which satisfy the
     *        judge function.
     *
     * @param judge The function which decides whether to remove the file.
     * @return int The number of files removed.
     */
    virtual int remove_source_files(auto judge(const std::string&)->bool) final;

    /**
     * @brief Find whether the file_path is in the source_files variable.
     *
     * @param file_path The file_path need to be found in the source_files.
     * @return true The file_path is in the source_files.
     * @return false The file_path is not in the source_files.
     */
    virtual bool find_source_file(const std::string& file_path) final;

  private:
    /**
     * @brief Compile a source file.
     *
     * @param project_cfg The config of the father project.
     * @param source_file The source file need to be compiled.
     */
    void compile_source_file(const ccc::config& project_cfg,
                             const std::filesystem::path& source_file);
};
} // namespace ccc

#endif
