#ifndef __BUILD_TARGET_H__
#define __BUILD_TARGET_H__

#include "ccc/config.h"
#include "ccc/dependency.h"

#include <filesystem>
#include <source_location>
#include <string>
#include <utility>
#include <vector>

namespace ccc {

/* The base class of all build targets.  */
class build_target : public ccc::config_manager {
  private:
    /* The name of the target. The final product is output_path / name. */
    std::string name;

    /* The directory for the final product. */
    std::filesystem::path output_path;

    /* The path for storing intermediate products. */
    std::filesystem::path obj_path = "./build/obj/";

    /* The source files of the target. */
    std::vector<std::filesystem::path> source_files;

    /* The intermediate products of the target.(Automatically generated by the
     * build_target class based on the source files, or can be added by
     * oneself.) */
    std::vector<std::filesystem::path> obj_files;

    /* This variable stores the name of the library required for this target. */
    std::vector<std::string> lib_files;

    /* The dependencies of the target. */
    std::vector<std::pair<ccc::build_target*, dependency_description>>
        dependencies;

    /* The location of the project */
    std::source_location loc;

    /* The status of the target. */
    std::vector<std::string> status;

    /* The simple information of the location. */
    std::string loc_info;

  public:
    /**
     * @brief Construct a new build target object.
     *
     * @param name The name of the target.
     * @param description The description of the target.
     * @param loc The location of the target.
     */
    build_target(std::string name, std::string description,
                 std::source_location loc);

    /**
     * @brief Construct a new build target object by copying another
     *        target object.
     *
     * @param other The build target object to be copied.
     */
    build_target(const build_target& other)
        : config_manager(other.config), name(other.name),
          output_path(other.output_path), obj_path(other.obj_path),
          source_files(other.source_files), obj_files(other.obj_files),
          lib_files(other.lib_files), dependencies(other.dependencies),
          loc(other.loc), status(other.status), loc_info(other.loc_info) {};

    /**
     * @brief Get the name of the build target.
     *
     * @return A const reference to the current target name, including
     *         platform prefixes and suffixes.
     */
    const std::string& get_name() const noexcept { return name; }

    /**
     * @brief Get the output directory of the build target.
     *
     * @return A const reference to the directory for the final product.
     */
    const std::filesystem::path& get_output_path() const noexcept {
        return output_path;
    }

    /**
     * @brief Get the object directory of the build target.
     *
     * @return A const reference to the directory for intermediate products.
     */
    const std::filesystem::path& get_obj_path() const noexcept {
        return obj_path;
    }

    /**
     * @brief Get the source files of the build target.
     *
     * @return A const reference to the source files.
     */
    const std::vector<std::filesystem::path>&
    get_source_files() const noexcept {
        return source_files;
    }

    /**
     * @brief Get the object files of the build target.
     *
     * @return A const reference to the generated and manually added object
     *         files.
     */
    const std::vector<std::filesystem::path>& get_obj_files() const noexcept {
        return obj_files;
    }

    /**
     * @brief Get the library names required by the build target.
     *
     * @return A const reference to the library names.
     */
    const std::vector<std::string>& get_lib_files() const noexcept {
        return lib_files;
    }

    /**
     * @brief Get the dependencies of the build target.
     *
     * @return A const reference to the dependency entries. The target
     *         pointers are non-owning.
     */
    const std::vector<std::pair<ccc::build_target*, dependency_description>>&
    get_dependencies() const noexcept {
        return dependencies;
    }

    /**
     * @brief Get the source location of the build target.
     *
     * @return The source location where the build target was declared.
     */
    std::source_location get_loc() const noexcept { return loc; }

    /**
     * @brief Get the errors recorded while building the target.
     *
     * @return A const reference to the recorded build errors.
     */
    const std::vector<std::string>& get_status() const noexcept {
        return status;
    }

    /**
     * @brief Get the simple information of the build target location.
     *
     * @return A const reference to the diagnostic information captured at
     *         construction.
     */
    const std::string& get_loc_info() const noexcept { return loc_info; }

    /**
     * @brief Set the output directory without changing other build state.
     *
     * @param path The directory for the final product.
     */
    void set_output_path(const std::filesystem::path& path) {
        output_path = path;
    }

    /**
     * @brief Set the object directory without changing other build state.
     *
     * @param path The directory for intermediate products.
     */
    void set_obj_path(const std::filesystem::path& path) { obj_path = path; }

    /**
     * @brief Add an object file or library artifact to the link inputs.
     *
     * @param path The path of the object file or library artifact.
     */
    void add_obj_file(const std::filesystem::path& path) {
        obj_files.push_back(path);
    }

    /**
     * @brief Add a library name to the link inputs.
     *
     * @param name The name of the library required by the build target.
     */
    void add_lib_file(const std::string& name) { lib_files.push_back(name); }

    /**
     * @brief Add a dependency to the build target.
     *
     * @param dep The dependency of the target.
     * @param is_transmit Whether add it directly to the build target.
     * @param is_compile Whether to actively  dependencies, if
     *                   dependencies do not exist.
     */
    void add_dependency(const ccc::build_target* dep, bool is_transmit,
                        bool is_compile = false) {
        dependencies.push_back(std::make_pair(
            const_cast<ccc::build_target*>(dep),
            ccc::dependency_description(is_transmit, is_compile)));
    }

    /**
     * @brief Compile all source files in source_files.
     *
     * @param project_cfg The config of the father project.
     * @param path The path indicating the compilation order relationship.
     */
    virtual void compile(const ccc::config& project_cfg,
                         std::vector<std::string>& path) final;

    /**
     * @brief The subclass needs to initialize the unset information in this
     * method based on the existing information.
     *
     * @param project_cfg The config of the father project.
     */
    virtual void init(const ccc::config& project_cfg) = 0;

    /**
     * @brief The subclass needs to implement this function, and the linking
     *        operation of the subclass needs to be implemented in this
     *        function.
     *
     * @param project_cfg The config of the father project.
     */
    virtual void link(const ccc::config& project_cfg) = 0;

    /**
     * @brief This method would call the compile and link methods.
     *
     * @param project_cfg The config of the father project.
     * @param path The path indicating the compilation order relationship.
     */
    virtual void process(const ccc::config& project_cfg,
                         std::vector<std::string>& path) final;

    /**
     * @brief The subclass needs to implement this function. When the parent
     * target wants to add a subtask directly to itself, this method will be
     * called.
     *
     * @param super The parent target.
     */
    virtual void transmit(ccc::build_target& super) = 0;

    /* The convenient utility functions provided by ccc. */

    /**
     * @brief Add file_path to the source_files variable.
     *
     * @param file_path The filesystem path of the source file to add.
     */
    virtual void add_source_file(const std::filesystem::path& file_path) final;

    /**
     * @brief Add these file_paths to the source_files variable.
     *
     * @param file_paths The filesystem paths of the source files to add.
     */
    virtual void add_source_files(
        const std::initializer_list<std::filesystem::path>& file_paths) final;

    /**
     * @brief Add all files in the dir_paths which have the suffix in suffixs to
     *        the the source_files variable.(Default recursion into subfolders.)
     *
     * @param dir_paths The filesystem paths of the directories to scan.
     * @param suffixs The suffixs of the files need to be added to the
     *        source_files variable.
     * @param recursive Decide whether to recursively enter subfolders.
     */
    virtual void add_source_files(
        const std::initializer_list<std::filesystem::path>& dir_paths,
        const std::initializer_list<std::string>& suffixs,
        bool recursive = true) final;

    /**
     * @brief Add all files in the dir_paths which satisfy the judge function to
     *        the the source_files variable.(Default recursion into subfolders.)
     *
     * @param dir_paths The filesystem paths of the directories to scan.
     * @param judge The function which receives a filesystem path and decides
     *              whether to add the file.
     * @param recursive Decide whether to recursively enter subfolders.
     */
    virtual void add_source_files(
        const std::initializer_list<std::filesystem::path>& dir_paths,
        auto judge(const std::filesystem::path&)->bool,
        bool recursive = true) final;

    /**
     * @brief Remove file_path from the source_files variable.
     *
     * @param file_path The filesystem path of the source file to remove.
     */
    virtual void
    remove_source_file(const std::filesystem::path& file_path) final;

    /**
     * @brief Remove these file_paths from the source_files variable.
     *
     * @param file_paths The filesystem paths of the source files to remove.
     */
    virtual void remove_source_files(
        const std::initializer_list<std::filesystem::path>& file_paths) final;

    /**
     * @brief Remove all files in the source_files variable which satisfy the
     *        judge function.
     *
     * @param judge The function which receives a filesystem path and decides
     *              whether to remove the file.
     * @return int The number of files removed.
     */
    virtual int
    remove_source_files(auto judge(const std::filesystem::path&)->bool) final;

    /**
     * @brief Find whether the file_path is in the source_files variable.
     *
     * @param file_path The filesystem path of the source file to find.
     * @return true The file_path is in the source_files.
     * @return false The file_path is not in the source_files.
     */
    virtual bool find_source_file(const std::filesystem::path& file_path) final;

  protected:
    /**
     * @brief Set the product name from a derived build target.
     *
     * @param value The platform-specific product name.
     */
    void set_name(const std::string& value) { name = value; }

    /**
     * @brief Add a build error from a derived build target.
     *
     * @param message The build error message.
     */
    void add_status(const std::string& message) { status.push_back(message); }

  private:
    /**
     * @brief Compile a source file.
     *
     * @param project_cfg The config of the father project.
     * @param source_file The source file need to be compiled.
     */
    void compile_source_file(const ccc::config& project_cfg,
                             const std::filesystem::path& source_file);
};
} // namespace ccc

#endif
